package edu.gcc.keen.tiles;

public enum TileStates
{
	CHEVRON_MIDDLE_TOP_SURFACE_TOP(0),
	CHEVRON_MIDDLE_TOP_SURFACE_BOTTOM(163),
	CHEVRON_MIDDLE_MIDDLE_SURFACE(0),
	CHEVRON_MIDDLE_BOTTOM_EDGE(0),
	CHEVRON_LEFT_TOP_EDGE_TOP(0),
	CHEVRON_LEFT_TOP_EDGE_BOTTOM(0),
	CHEVRON_LEFT_MIDDLE_EDGE(0),
	CHEVRON_LEFT_BOTTOM_EDGE(0),
	CHEVRON_RIGHT_TOP_EDGE_TOP(0),
	CHEVRON_RIGHT_TOP_EDGE_BOTTOM(162),
	CHEVRON_RIGHT_MIDDLE_EDGE_TOP(0),
	CHEVRON_RIGHT_MIDDLE_EDGE_BOTTOM(165),
	CHEVRON_RIGHT_BOTTOM_EDGE_TOP(0),
	CHEVRON_RIGHT_BOTTOM_EDGE_BOTTOM(166),
	CHEVRON_RIGHT_BOTTOM_EDGE_EXTRA(0);

	private int index;

	private TileStates(int index)
	{
		this.index = index;
	}

	public int getIndex()
	{
		return index;
	}
}
